# Generated by Django 4.0.4 on 2022-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quality_inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('p_name', models.CharField(blank=True, max_length=90)),
                ('department', models.CharField(blank=True, max_length=90)),
                ('inspected_no', models.IntegerField(blank=True, null=True)),
                ('noninspected_no', models.IntegerField(blank=True, null=True)),
                ('inspected_by', models.CharField(blank=True, max_length=90, null=True)),
                ('qualified_products', models.IntegerField(blank=True, null=True)),
                ('nonqualified_products', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
