# Generated by Django 4.0.4 on 2022-06-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_quality_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_inspection',
            name='sku',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
