# Generated by Django 4.0.4 on 2022-06-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_quality_inspection_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='quality_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_date', models.DateField()),
                ('qc_pname', models.CharField(blank=True, max_length=90)),
                ('qc_sku', models.CharField(blank=True, max_length=90)),
                ('qc_custumername', models.CharField(blank=True, max_length=90)),
                ('qc_inspdate', models.CharField(blank=True, max_length=90)),
            ],
        ),
    ]
