# Generated by Django 4.0.4 on 2022-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_quality_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_pname', models.CharField(blank=True, max_length=90)),
                ('pm_discription', models.CharField(blank=True, max_length=90)),
                ('pm_quantity', models.CharField(blank=True, max_length=90)),
                ('pm_start_date', models.DateField()),
                ('pm_end_date', models.DateField()),
                ('pm_estcost', models.CharField(blank=True, max_length=90)),
                ('pm_estcostpitem', models.CharField(blank=True, max_length=90)),
            ],
        ),
    ]
