# Generated by Django 4.0.4 on 2022-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_complaint_against_supplier_customercomplaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expences',
            name='paymdate',
            field=models.DateField(max_length=100),
        ),
    ]
